export type IB24AvailableMethods =
  | 'user.current'
  | 'user.get'
  | 'crm.lead.get'
  | 'crm.lead.list'
  | 'crm.lead.update'
  | 'crm.lead.add'
  | 'crm.deal.fields'
  | 'crm.stagehistory.list'
  | 'tasks.task.add'
  | 'tasks.task.list'
  | 'tasks.task.get'
  | 'tasks.task.delete'
  | 'tasks.task.complete'
  | 'tasks.task.result.list'
  | 'tasks.task.disapprove'
  | 'tasks.task.approve'
  | 'tasks.task.update'
  | 'department.get'
  | 'crm.deal.list'
  | 'crm.deal.add'
  | 'crm.deal.get'
  | 'crm.deal.update'
  | 'im.message.add'
  | 'imbot.command.register'
  | 'im.message.delete'
  | 'im.message.update'
  | 'imbot.command.unregister'
  | 'crm.duplicate.findbycomm'
  | 'imbot.register'
  | 'imbot.unregister'
  | 'imbot.message.add'
  | 'imbot.message.update'
  | 'imbot.bot.list'
  | 'placement.bind'
  | 'placement.unbind'
  | 'placement.get'
  | 'event.bind'
  | 'event.unbind'
  | 'crm.timeline.comment.add'
  | 'crm.timeline.comment.list'
  | 'crm.timeline.item.pin'
  | 'crm.timeline.item.unpin'
  | 'crm.activity.add'
  | 'event.get'
  | 'im.notify.personal.add'
  | 'im.notify.system.add'
  | 'crm.contact.list'
  | 'crm.item.list'
  | 'crm.item.update'
  | 'crm.company.list'
  | 'crm.activity.list'
  | 'crm.activity.update'
  | 'crm.activity.todo.update'
  | 'crm.activity.todo.updateResponsibleUser'
  | 'crm.category.list'
  | 'crm.dealcategory.stage.list';

export interface IB24Timestamp {
  start: number;
  finish: number;
  duration: number;
  processing: number;
  date_start: string;
  date_finish: string;
  operating_reset_at: number;
  operating: number;
}