export const B24Emoji = {
  REFUSAL: '❌',
  SUCCESS: '✅',
  HR: {
    HEADHUNTER: {
      RESPONSE: '🟢',
      INVITE: '🟠',
      BOT: '🟡',
      ATTENTION: '❗',
    },
  },
};

export const B24Categories = {
  SITES: '0',
  SETTING_ADVERT: '1',
  ADVERT: '10',
  SEO_BASE: '34',
  SEO_INNER: '7',
  SEO_OUT: '16',
  HR: '14',
};

export const B24PORTS = {
  BITRIX: 'BITRIX_PORT',
  DEALS: {
    DEALS_DEFAULT: 'DEALS_PORT',
  },
  DEPARTMENTS: {
    DEPARTMENT_DEFAULT: 'DEPARTMENTS_PORT',
  },
  EVENTS: {
    EVENTS_DEFAULT: 'EVENTS_PORT',
  },
  TASKS: {
    TASKS_DEFAULT: 'TASKS_PORT',
  },
  MESSAGES: {
    MESSAGES_DEFAULT: 'MESSAGES_PORT',
  },
  BOT: {
    BOT_DEFAULT: 'BOT_PORT',
    BOT_COMMANDS_REPOSITORY: 'BOT_COMMANDS_REPOSITORY_PORT',
  },
  USERS: {
    USERS_DEFAULT: 'USERS_PORT',
  },
  LEADS: {
    LEADS_DEFAULT: 'LEADS_PORT',
    UPSELLS_REPOSITORY: 'LEADS_UPSELLS_REPOSITORY_PORT',
    MANAGER_CALLING_REPOSITORY: 'LEADS_MANAGER_CALLING_REPOSITORY_PORT',
  },
  PLACEMENTS: {
    PLACEMENTS_DEFAULT: 'PLACEMENTS_PORT',
  },
  WIKI: {
    WIKI_CLIENT_PAYMENTS_REPOSITORY: 'WIKI_CLIENT_PAYMENTS_REPOSITORY_PORT',
  },
  HEADHUNTER: {
    HH_VACANCIES_REPOSITORY: 'HH_VACANCIES_REPOSITORY_PORT',
  },
};
