export const HH_WEBHOOK_EVENTS = {
  NEW_RESPONSE_OR_INVITATION_VACANCY: 'NEW_RESPONSE_OR_INVITATION_VACANCY',
  NEW_NEGOTIATION_VACANCY: 'NEW_NEGOTIATION_VACANCY',
  NEGOTIATION_EMPLOYER_STATE_CHANGE: 'NEGOTIATION_EMPLOYER_STATE_CHANGE',
};
