import { IB24CRMMultiField } from '../../../../interfaces/api/interface';

export type IB24Lead = IB24LeadDefault & IB24LeadV2 & Record<string, any>;

export interface IB24LeadDefault {
  ID: string;
  ASSIGNED_BY_ID: string;
  STATUS_ID: string;
  DATE_CREATE: string;
  PHONE: Omit<IB24CRMMultiField, 'ID' | 'TYPE_ID'>[];
  COMMENTS?: string;
  MOVED_TIME: string;
}

interface IB24LeadV2 {
  id: number;
  createdTime: string;
  dateCreateShort: string | null;
  updatedTime: string;
  dateModifyShort: string | null;
  createdBy: number;
  updatedBy: number;
  assignedById: number;
  opened: string;
  companyId: number;
  contactId: number;
  stageId: string;
  isConvert: string | null;
  statusDescription: string | null;
  stageSemanticId: string;
  productId: string | null;
  opportunity: number;
  currencyId: string;
  sourceId: string;
  sourceDescription: string;
  title: string;
  name: string;
  lastName: string;
  secondName: string;
  shortName: string | null;
  companyTitle: string;
  post: string;
  address: string | null;
  comments: string;
  webformId: number;
  originatorId: string | null;
  originId: string | null;
  dateClosed: string | null;
  birthdate: string;
  honorific: string;
  hasPhone: string;
  hasEmail: string;
  hasImol: string;
  login: string | null;
  isReturnCustomer: string;
  searchContent: string;
  isManualOpportunity: string;
  movedBy: number;
  movedTime: string;
  lastActivityBy: number;
  lastActivityTime: string;
  phoneMobile: string;
  phoneWork: string;
  phoneMailing: string;
  emailHome: string;
  emailWork: string;
  emailMailing: string;
  skype: string | null;
  icq: string | null;
  imol: string;
  email: string;
  phone: string;
  ufCrm_1720019876534: string;
  parentId1222: string | null;
  parentId1226: string | null;
  parentId1228: string | null;
  parentId1236: string | null;
  parentId1238: string | null;
  parentId1240: string | null;
  parentId1244: string | null;
  parentId1246: string | null;
  parentId1254: string | null;
  parentId1256: string | null;
  utmSource: string | null;
  utmMedium: string | null;
  utmCampaign: string | null;
  utmContent: string | null;
  utmTerm: string | null;
  observers: unknown[];
  contactIds: unknown[];
  entityTypeId: number;
}
